# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rspec', '~> 3.5'
gem 'rspec-core', '~> 3.4', '>= 3.4.4'
gem 'tty-prompt', '~> 0.23.0'
gem 'bcrypt', '~> 3.1', '>= 3.1.12'
gem 'byebug', '~> 9.0', '>= 9.0.6'
gem 'ascii-charts', '~> 0.9.2'
